/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuildRouteImport } from './routes/build'
import { Route as ImageRouteImport } from './routes/image'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VideoRouteImport } from './routes/video'
import { Route as VideoAgentRouteImport } from './routes/video-agent'
import { Route as AuthenticatedGettingReadyRouteImport } from './routes/_authenticated/getting-ready'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as VirtualModelIndexRouteImport } from './routes/virtual-model.index'
import { Route as VirtualModelCreateModelRouteImport } from './routes/virtual-model.create-model'
import { Route as AuthenticatedCopilotIndexRouteImport } from './routes/_authenticated/copilot.index'
import { Route as AuthenticatedCopilotChatIdRouteImport } from './routes/_authenticated/copilot.$chatId'
import { Route as AuthenticatedCopilotHistoryRouteImport } from './routes/_authenticated/copilot.history'
import { Route as AuthenticatedWorkflowsIndexRouteImport } from './routes/_authenticated/workflows.index'
import { Route as AuthenticatedWorkflowsCreateRouteImport } from './routes/_authenticated/workflows.create'
import { Route as OauthGoogleReturnRouteImport } from './routes/oauth/google/return'
import { Route as OauthMetaReturnRouteImport } from './routes/oauth/meta/return'
import { Route as ApiPublicJobsWorkerRouteImport } from './routes/api/public/jobs/worker'
import { Route as ApiPublicPipelineRenderRouteImport } from './routes/api/public/pipeline/render'
import { Route as ApiPublicPipelineTickRouteImport } from './routes/api/public/pipeline/tick'
import { Route as ApiPublicWorkflowsSchedulerRouteImport } from './routes/api/public/workflows/scheduler'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoAgentRoute = VideoAgentRouteImport.update({
  id: '/video-agent',
  path: '/video-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGettingReadyRoute =
  AuthenticatedGettingReadyRouteImport.update({
    id: '/getting-ready',
    path: '/getting-ready',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const VirtualModelIndexRoute = VirtualModelIndexRouteImport.update({
  id: '/virtual-model/',
  path: '/virtual-model/',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualModelCreateModelRoute = VirtualModelCreateModelRouteImport.update({
  id: '/virtual-model/create-model',
  path: '/virtual-model/create-model',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCopilotIndexRoute =
  AuthenticatedCopilotIndexRouteImport.update({
    id: '/copilot/',
    path: '/copilot/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotChatIdRoute =
  AuthenticatedCopilotChatIdRouteImport.update({
    id: '/copilot/$chatId',
    path: '/copilot/$chatId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCopilotHistoryRoute =
  AuthenticatedCopilotHistoryRouteImport.update({
    id: '/copilot/history',
    path: '/copilot/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowsIndexRoute =
  AuthenticatedWorkflowsIndexRouteImport.update({
    id: '/workflows/',
    path: '/workflows/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkflowsCreateRoute =
  AuthenticatedWorkflowsCreateRouteImport.update({
    id: '/workflows/create',
    path: '/workflows/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const OauthGoogleReturnRoute = OauthGoogleReturnRouteImport.update({
  id: '/oauth/google/return',
  path: '/oauth/google/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthMetaReturnRoute = OauthMetaReturnRouteImport.update({
  id: '/oauth/meta/return',
  path: '/oauth/meta/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsWorkerRoute = ApiPublicJobsWorkerRouteImport.update({
  id: '/api/public/jobs/worker',
  path: '/api/public/jobs/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPipelineRenderRoute = ApiPublicPipelineRenderRouteImport.update({
  id: '/api/public/pipeline/render',
  path: '/api/public/pipeline/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPipelineTickRoute = ApiPublicPipelineTickRouteImport.update({
  id: '/api/public/pipeline/tick',
  path: '/api/public/pipeline/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkflowsSchedulerRoute =
  ApiPublicWorkflowsSchedulerRouteImport.update({
    id: '/api/public/workflows/scheduler',
    path: '/api/public/workflows/scheduler',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/image': typeof ImageRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/video': typeof VideoRoute
  '/video-agent': typeof VideoAgentRoute
  '/getting-ready': typeof AuthenticatedGettingReadyRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/virtual-model/create-model': typeof VirtualModelCreateModelRoute
  '/virtual-model/': typeof VirtualModelIndexRoute
  '/copilot/$chatId': typeof AuthenticatedCopilotChatIdRoute
  '/copilot/history': typeof AuthenticatedCopilotHistoryRoute
  '/workflows/create': typeof AuthenticatedWorkflowsCreateRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/oauth/meta/return': typeof OauthMetaReturnRoute
  '/copilot/': typeof AuthenticatedCopilotIndexRoute
  '/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/api/public/jobs/worker': typeof ApiPublicJobsWorkerRoute
  '/api/public/pipeline/render': typeof ApiPublicPipelineRenderRoute
  '/api/public/pipeline/tick': typeof ApiPublicPipelineTickRoute
  '/api/public/workflows/scheduler': typeof ApiPublicWorkflowsSchedulerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/image': typeof ImageRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/video': typeof VideoRoute
  '/video-agent': typeof VideoAgentRoute
  '/getting-ready': typeof AuthenticatedGettingReadyRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/virtual-model/create-model': typeof VirtualModelCreateModelRoute
  '/virtual-model': typeof VirtualModelIndexRoute
  '/copilot/$chatId': typeof AuthenticatedCopilotChatIdRoute
  '/copilot/history': typeof AuthenticatedCopilotHistoryRoute
  '/workflows/create': typeof AuthenticatedWorkflowsCreateRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/oauth/meta/return': typeof OauthMetaReturnRoute
  '/copilot': typeof AuthenticatedCopilotIndexRoute
  '/workflows': typeof AuthenticatedWorkflowsIndexRoute
  '/api/public/jobs/worker': typeof ApiPublicJobsWorkerRoute
  '/api/public/pipeline/render': typeof ApiPublicPipelineRenderRoute
  '/api/public/pipeline/tick': typeof ApiPublicPipelineTickRoute
  '/api/public/workflows/scheduler': typeof ApiPublicWorkflowsSchedulerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/audio': typeof AudioRoute
  '/auth': typeof AuthRoute
  '/build': typeof BuildRoute
  '/image': typeof ImageRoute
  '/library': typeof LibraryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/video': typeof VideoRoute
  '/video-agent': typeof VideoAgentRoute
  '/_authenticated/getting-ready': typeof AuthenticatedGettingReadyRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/virtual-model/create-model': typeof VirtualModelCreateModelRoute
  '/virtual-model/': typeof VirtualModelIndexRoute
  '/_authenticated/copilot/$chatId': typeof AuthenticatedCopilotChatIdRoute
  '/_authenticated/copilot/history': typeof AuthenticatedCopilotHistoryRoute
  '/_authenticated/workflows/create': typeof AuthenticatedWorkflowsCreateRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/oauth/meta/return': typeof OauthMetaReturnRoute
  '/_authenticated/copilot/': typeof AuthenticatedCopilotIndexRoute
  '/_authenticated/workflows/': typeof AuthenticatedWorkflowsIndexRoute
  '/api/public/jobs/worker': typeof ApiPublicJobsWorkerRoute
  '/api/public/pipeline/render': typeof ApiPublicPipelineRenderRoute
  '/api/public/pipeline/tick': typeof ApiPublicPipelineTickRoute
  '/api/public/workflows/scheduler': typeof ApiPublicWorkflowsSchedulerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio'
    | '/auth'
    | '/build'
    | '/image'
    | '/library'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/verify'
    | '/video'
    | '/video-agent'
    | '/getting-ready'
    | '/integrations'
    | '/virtual-model/create-model'
    | '/virtual-model/'
    | '/copilot/$chatId'
    | '/copilot/history'
    | '/workflows/create'
    | '/oauth/google/return'
    | '/oauth/meta/return'
    | '/copilot/'
    | '/workflows/'
    | '/api/public/jobs/worker'
    | '/api/public/pipeline/render'
    | '/api/public/pipeline/tick'
    | '/api/public/workflows/scheduler'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio'
    | '/auth'
    | '/build'
    | '/image'
    | '/library'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/verify'
    | '/video'
    | '/video-agent'
    | '/getting-ready'
    | '/integrations'
    | '/virtual-model/create-model'
    | '/virtual-model'
    | '/copilot/$chatId'
    | '/copilot/history'
    | '/workflows/create'
    | '/oauth/google/return'
    | '/oauth/meta/return'
    | '/copilot'
    | '/workflows'
    | '/api/public/jobs/worker'
    | '/api/public/pipeline/render'
    | '/api/public/pipeline/tick'
    | '/api/public/workflows/scheduler'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/audio'
    | '/auth'
    | '/build'
    | '/image'
    | '/library'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/verify'
    | '/video'
    | '/video-agent'
    | '/_authenticated/getting-ready'
    | '/_authenticated/integrations'
    | '/virtual-model/create-model'
    | '/virtual-model/'
    | '/_authenticated/copilot/$chatId'
    | '/_authenticated/copilot/history'
    | '/_authenticated/workflows/create'
    | '/oauth/google/return'
    | '/oauth/meta/return'
    | '/_authenticated/copilot/'
    | '/_authenticated/workflows/'
    | '/api/public/jobs/worker'
    | '/api/public/pipeline/render'
    | '/api/public/pipeline/tick'
    | '/api/public/workflows/scheduler'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AudioRoute: typeof AudioRoute
  AuthRoute: typeof AuthRoute
  BuildRoute: typeof BuildRoute
  ImageRoute: typeof ImageRoute
  LibraryRoute: typeof LibraryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  VideoRoute: typeof VideoRoute
  VideoAgentRoute: typeof VideoAgentRoute
  VirtualModelCreateModelRoute: typeof VirtualModelCreateModelRoute
  VirtualModelIndexRoute: typeof VirtualModelIndexRoute
  OauthGoogleReturnRoute: typeof OauthGoogleReturnRoute
  OauthMetaReturnRoute: typeof OauthMetaReturnRoute
  ApiPublicJobsWorkerRoute: typeof ApiPublicJobsWorkerRoute
  ApiPublicPipelineRenderRoute: typeof ApiPublicPipelineRenderRoute
  ApiPublicPipelineTickRoute: typeof ApiPublicPipelineTickRoute
  ApiPublicWorkflowsSchedulerRoute: typeof ApiPublicWorkflowsSchedulerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-agent': {
      id: '/video-agent'
      path: '/video-agent'
      fullPath: '/video-agent'
      preLoaderRoute: typeof VideoAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/getting-ready': {
      id: '/_authenticated/getting-ready'
      path: '/getting-ready'
      fullPath: '/getting-ready'
      preLoaderRoute: typeof AuthenticatedGettingReadyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/virtual-model/': {
      id: '/virtual-model/'
      path: '/virtual-model'
      fullPath: '/virtual-model/'
      preLoaderRoute: typeof VirtualModelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-model/create-model': {
      id: '/virtual-model/create-model'
      path: '/virtual-model/create-model'
      fullPath: '/virtual-model/create-model'
      preLoaderRoute: typeof VirtualModelCreateModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/copilot/': {
      id: '/_authenticated/copilot/'
      path: '/copilot'
      fullPath: '/copilot/'
      preLoaderRoute: typeof AuthenticatedCopilotIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/$chatId': {
      id: '/_authenticated/copilot/$chatId'
      path: '/copilot/$chatId'
      fullPath: '/copilot/$chatId'
      preLoaderRoute: typeof AuthenticatedCopilotChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot/history': {
      id: '/_authenticated/copilot/history'
      path: '/copilot/history'
      fullPath: '/copilot/history'
      preLoaderRoute: typeof AuthenticatedCopilotHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows/': {
      id: '/_authenticated/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows/create': {
      id: '/_authenticated/workflows/create'
      path: '/workflows/create'
      fullPath: '/workflows/create'
      preLoaderRoute: typeof AuthenticatedWorkflowsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/google/return': {
      id: '/oauth/google/return'
      path: '/oauth/google/return'
      fullPath: '/oauth/google/return'
      preLoaderRoute: typeof OauthGoogleReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/meta/return': {
      id: '/oauth/meta/return'
      path: '/oauth/meta/return'
      fullPath: '/oauth/meta/return'
      preLoaderRoute: typeof OauthMetaReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/worker': {
      id: '/api/public/jobs/worker'
      path: '/api/public/jobs/worker'
      fullPath: '/api/public/jobs/worker'
      preLoaderRoute: typeof ApiPublicJobsWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pipeline/render': {
      id: '/api/public/pipeline/render'
      path: '/api/public/pipeline/render'
      fullPath: '/api/public/pipeline/render'
      preLoaderRoute: typeof ApiPublicPipelineRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pipeline/tick': {
      id: '/api/public/pipeline/tick'
      path: '/api/public/pipeline/tick'
      fullPath: '/api/public/pipeline/tick'
      preLoaderRoute: typeof ApiPublicPipelineTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workflows/scheduler': {
      id: '/api/public/workflows/scheduler'
      path: '/api/public/workflows/scheduler'
      fullPath: '/api/public/workflows/scheduler'
      preLoaderRoute: typeof ApiPublicWorkflowsSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGettingReadyRoute: typeof AuthenticatedGettingReadyRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedCopilotChatIdRoute: typeof AuthenticatedCopilotChatIdRoute
  AuthenticatedCopilotHistoryRoute: typeof AuthenticatedCopilotHistoryRoute
  AuthenticatedWorkflowsCreateRoute: typeof AuthenticatedWorkflowsCreateRoute
  AuthenticatedCopilotIndexRoute: typeof AuthenticatedCopilotIndexRoute
  AuthenticatedWorkflowsIndexRoute: typeof AuthenticatedWorkflowsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGettingReadyRoute: AuthenticatedGettingReadyRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedCopilotChatIdRoute: AuthenticatedCopilotChatIdRoute,
  AuthenticatedCopilotHistoryRoute: AuthenticatedCopilotHistoryRoute,
  AuthenticatedWorkflowsCreateRoute: AuthenticatedWorkflowsCreateRoute,
  AuthenticatedCopilotIndexRoute: AuthenticatedCopilotIndexRoute,
  AuthenticatedWorkflowsIndexRoute: AuthenticatedWorkflowsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AudioRoute: AudioRoute,
  AuthRoute: AuthRoute,
  BuildRoute: BuildRoute,
  ImageRoute: ImageRoute,
  LibraryRoute: LibraryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  VideoRoute: VideoRoute,
  VideoAgentRoute: VideoAgentRoute,
  VirtualModelCreateModelRoute: VirtualModelCreateModelRoute,
  VirtualModelIndexRoute: VirtualModelIndexRoute,
  OauthGoogleReturnRoute: OauthGoogleReturnRoute,
  OauthMetaReturnRoute: OauthMetaReturnRoute,
  ApiPublicJobsWorkerRoute: ApiPublicJobsWorkerRoute,
  ApiPublicPipelineRenderRoute: ApiPublicPipelineRenderRoute,
  ApiPublicPipelineTickRoute: ApiPublicPipelineTickRoute,
  ApiPublicWorkflowsSchedulerRoute: ApiPublicWorkflowsSchedulerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
